on:
  workflow_dispatch:

  push:
    branches: [main]

name: Release

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Cancel ongoing builds
        uses: styfle/cancel-workflow-action@0.9.0

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Download dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
        env:
          HUSKY_SKIP_INSTALL: true

      - name: Run validate script
        run: npm run validate

      - name: Zip bash script
        run: |
          tar -czvf dotenv-op.tar.gz dotenv-op.sh

      - name: 🚀
        uses: cycjimmy/semantic-release-action@v3
        id: create_release
        with:
          semantic_version: 18
          branches: |
            [
              'main',
            ]
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
