name: Lint

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  run-shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Download dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
        env:
          HUSKY_SKIP_INSTALL: true

      - name: Run validate script
        run: npm run validate
